const encoder=new TextEncoder();
const json=(data,status=200)=>new Response(JSON.stringify(data),{status,headers:{'content-type':'application/json; charset=utf-8'}});
const text=v=>String(v??'').trim();
const b64url=bytes=>btoa(String.fromCharCode(...bytes)).replace(/=/g,'').replace(/\+/g,'-').replace(/\//g,'_');
const fromB64url=value=>Uint8Array.from(atob(value.replace(/-/g,'+').replace(/_/g,'/')),c=>c.charCodeAt(0));
async function hmac(value,secret){const key=await crypto.subtle.importKey('raw',encoder.encode(secret),{name:'HMAC',hash:'SHA-256'},false,['sign']);return new Uint8Array(await crypto.subtle.sign('HMAC',key,encoder.encode(value)))}
async function tokenSign(payload,secret){const head=b64url(encoder.encode(JSON.stringify({alg:'HS256',typ:'JWT'}))),body=b64url(encoder.encode(JSON.stringify({...payload,exp:Math.floor(Date.now()/1000)+28800}))),value=head+'.'+body;return value+'.'+b64url(await hmac(value,secret))}
async function tokenVerify(token,secret){const [head,body,signature]=String(token||'').split('.');if(!head||!body||!signature)throw new Error('TOKEN');const expected=await hmac(head+'.'+body,secret),received=fromB64url(signature);if(received.length!==expected.length||!crypto.subtle.timingSafeEqual?.(received,expected)){let diff=received.length^expected.length;for(let i=0;i<Math.min(received.length,expected.length);i++)diff|=received[i]^expected[i];if(diff)throw new Error('TOKEN')}const payload=JSON.parse(new TextDecoder().decode(fromB64url(body)));if(payload.exp<Math.floor(Date.now()/1000))throw new Error('TOKEN');return payload}
async function passwordHash(password,salt=crypto.getRandomValues(new Uint8Array(16))){const key=await crypto.subtle.importKey('raw',encoder.encode(password),'PBKDF2',false,['deriveBits']),bits=await crypto.subtle.deriveBits({name:'PBKDF2',salt,iterations:100000,hash:'SHA-256'},key,256);return b64url(salt)+'.'+b64url(new Uint8Array(bits))}
async function passwordCheck(password,stored){const [salt]=String(stored||'').split('.');if(!salt)return false;return stored===await passwordHash(password,fromB64url(salt))}
async function jwtSecret(env){if(env.JWT_SECRET)return env.JWT_SECRET;const row=await env.DB.prepare("SELECT valor FROM configuracoes WHERE chave='jwt_secret'").first();return row?.valor||'trocar-em-producao'}
async function auth(request,env){try{return await tokenVerify((request.headers.get('authorization')||'').replace('Bearer ',''),await jwtSecret(env))}catch{return null}}

async function ensureSchema(env){if(!env.DB)throw new Error('Banco D1 não configurado');await env.DB.exec(`
CREATE TABLE IF NOT EXISTS usuarios(id INTEGER PRIMARY KEY AUTOINCREMENT,nome TEXT NOT NULL,email TEXT NOT NULL UNIQUE,senha_hash TEXT NOT NULL,setor TEXT,perfil TEXT NOT NULL,ativo INTEGER NOT NULL DEFAULT 1);
CREATE TABLE IF NOT EXISTS configuracoes(chave TEXT PRIMARY KEY,valor TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS locais(id INTEGER PRIMARY KEY AUTOINCREMENT,nome TEXT NOT NULL UNIQUE,tipo TEXT NOT NULL,ativo INTEGER NOT NULL DEFAULT 1);
CREATE TABLE IF NOT EXISTS equipamentos(id INTEGER PRIMARY KEY AUTOINCREMENT,tag TEXT NOT NULL UNIQUE,nome TEXT NOT NULL,tipo_propriedade TEXT NOT NULL,fornecedor TEXT);
CREATE TABLE IF NOT EXISTS ciclos(id INTEGER PRIMARY KEY AUTOINCREMENT,equipamento_id INTEGER NOT NULL,numero INTEGER NOT NULL,destino_id INTEGER,os TEXT,processo TEXT NOT NULL,status TEXT NOT NULL,proxima_acao TEXT,prioridade TEXT NOT NULL,aguardando_terceiro INTEGER NOT NULL DEFAULT 0,aberto_em TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,ultima_movimentacao_em TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,finalizado_em TEXT,criado_por INTEGER,UNIQUE(equipamento_id,numero));
CREATE UNIQUE INDEX IF NOT EXISTS uq_ciclo_ativo ON ciclos(equipamento_id) WHERE finalizado_em IS NULL;
CREATE TABLE IF NOT EXISTS historico(id INTEGER PRIMARY KEY AUTOINCREMENT,ciclo_id INTEGER NOT NULL,usuario_id INTEGER,status_anterior TEXT,status_novo TEXT NOT NULL,observacao TEXT,criado_em TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS solicitacoes_senha(id INTEGER PRIMARY KEY AUTOINCREMENT,email TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'Pendente',criado_em TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS analises_ux(id INTEGER PRIMARY KEY AUTOINCREMENT,tela TEXT NOT NULL,contexto TEXT,resultado TEXT NOT NULL,criado_por INTEGER,criado_em TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS sugestoes_ux(id INTEGER PRIMARY KEY AUTOINCREMENT,analise_id INTEGER,categoria TEXT NOT NULL,prioridade TEXT NOT NULL,problema TEXT NOT NULL,recomendacao TEXT NOT NULL,impacto TEXT,status TEXT NOT NULL DEFAULT 'Pendente',responsavel_id INTEGER,decidido_por INTEGER,justificativa TEXT,criado_em TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,atualizado_em TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS feedback_ux(id INTEGER PRIMARY KEY AUTOINCREMENT,tela TEXT NOT NULL,comentario TEXT NOT NULL,avaliacao INTEGER,usuario_id INTEGER,criado_em TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS padroes_design(id INTEGER PRIMARY KEY AUTOINCREMENT,categoria TEXT NOT NULL,regra TEXT NOT NULL,versao TEXT NOT NULL DEFAULT '1.0',ativo INTEGER NOT NULL DEFAULT 1);
CREATE TABLE IF NOT EXISTS historico_sugestoes_ux(id INTEGER PRIMARY KEY AUTOINCREMENT,sugestao_id INTEGER NOT NULL,status_anterior TEXT,status_novo TEXT NOT NULL,usuario_id INTEGER,justificativa TEXT,criado_em TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
`);let secret=await env.DB.prepare("SELECT valor FROM configuracoes WHERE chave='jwt_secret'").first();if(!secret){await env.DB.prepare("INSERT INTO configuracoes(chave,valor) VALUES('jwt_secret',?)").bind(b64url(crypto.getRandomValues(new Uint8Array(48)))).run()}const user=await env.DB.prepare('SELECT id FROM usuarios LIMIT 1').first();if(!user&&env.ADMIN_EMAIL&&env.ADMIN_PASSWORD){await env.DB.prepare('INSERT INTO usuarios(nome,email,senha_hash,setor,perfil) VALUES(?,?,?,?,?)').bind(env.ADMIN_NAME||'Administrador',text(env.ADMIN_EMAIL).toLowerCase(),await passwordHash(env.ADMIN_PASSWORD),'Almoxarifado','Administrador').run()}const local=await env.DB.prepare('SELECT id FROM locais LIMIT 1').first();if(!local){await env.DB.batch([['P-74','Plataforma'],['P-80','Plataforma'],['Base','Base'],['Fornecedor','Fornecedor'],['Estoque / Almoxarifado','Estoque']].map(([n,t])=>env.DB.prepare('INSERT INTO locais(nome,tipo) VALUES(?,?)').bind(n,t)))}const padrao=await env.DB.prepare('SELECT id FROM padroes_design LIMIT 1').first();if(!padrao){const rows=[['Cores','Usar azul-marinho na estrutura principal e ciano nas ações primárias.'],['Cores','Reservar amarelo para atenção, vermelho para crítico ou atraso e verde para concluído ou liberado.'],['Acessibilidade','Nunca comunicar um status apenas por cor; combinar texto e ícone.'],['Hierarquia','Manter uma ação principal evidente por tela e reduzir elementos concorrentes.'],['Consistência','Padronizar tipografia, espaçamento, botões, filtros, tabelas e cartões.']];await env.DB.batch(rows.map(x=>env.DB.prepare('INSERT INTO padroes_design(categoria,regra) VALUES(?,?)').bind(...x)))}}

async function body(request){return request.json().catch(()=>({}))}
async function api(request,env,path){await ensureSchema(env);const method=request.method;
if(path==='/api/setup'&&method==='POST'){const existe=await env.DB.prepare('SELECT id FROM usuarios LIMIT 1').first();if(existe)return json({erro:'O administrador inicial já foi cadastrado.'},409);const x=await body(request),nome=text(x.nome),email=text(x.email).toLowerCase(),senha=String(x.senha||'');if(!nome||!email.includes('@')||senha.length<8)return json({erro:'Informe nome, e-mail válido e senha com pelo menos 8 caracteres.'},400);await env.DB.prepare('INSERT INTO usuarios(nome,email,senha_hash,setor,perfil) VALUES(?,?,?,?,?)').bind(nome,email,await passwordHash(senha),'Almoxarifado','Administrador').run();return json({ok:true})}
if(path==='/api/cadastro'&&method==='POST'){const x=await body(request),nome=text(x.nome),email=text(x.email).toLowerCase(),senha=String(x.password||''),setor=text(x.setor);if(!nome||!email.includes('@')||!setor||senha.length<8)return json({erro:'Preencha todos os campos e use uma senha com pelo menos 8 caracteres.'},400);try{const r=await env.DB.prepare('INSERT INTO usuarios(nome,email,senha_hash,setor,perfil,ativo) VALUES(?,?,?,?,?,0)').bind(nome,email,await passwordHash(senha),setor,'Operacional').run();return json({id:r.meta.last_row_id,mensagem:'Cadastro enviado. Aguarde a aprovação de um administrador.'},201)}catch(e){if(/unique/i.test(String(e.message)))return json({erro:'Este e-mail já está cadastrado.'},409);throw e}}
if(path==='/api/login'&&method==='POST'){const x=await body(request),u=await env.DB.prepare('SELECT * FROM usuarios WHERE lower(email)=lower(?) AND ativo=1').bind(x.email||'').first();if(!u||!await passwordCheck(x.password||'',u.senha_hash))return json({erro:'E-mail ou senha inválidos'},401);return json({token:await tokenSign({id:u.id,nome:u.nome,perfil:u.perfil},await jwtSecret(env)),usuario:{id:u.id,nome:u.nome,email:u.email,perfil:u.perfil,setor:u.setor}})}
const user=await auth(request,env);if(!user)return json({erro:'Não autenticado'},401);
if(path==='/api/locais'&&method==='GET')return json((await env.DB.prepare('SELECT * FROM locais ORDER BY nome').all()).results);
if(path==='/api/ciclos'&&method==='GET')return json((await env.DB.prepare(`SELECT c.*,e.tag,e.nome equipamento,l.nome destino FROM ciclos c JOIN equipamentos e ON e.id=c.equipamento_id LEFT JOIN locais l ON l.id=c.destino_id ORDER BY c.id DESC`).all()).results);
if(path==='/api/ciclos'&&method==='POST'){const x=await body(request),tag=text(x.tag).toUpperCase();if(!tag||!x.equipamento||!x.destino_id)return json({erro:'TAG, equipamento e destino são obrigatórios'},400);let eq=await env.DB.prepare('SELECT * FROM equipamentos WHERE tag=?').bind(tag).first();if(!eq){const r=await env.DB.prepare('INSERT INTO equipamentos(tag,nome,tipo_propriedade,fornecedor) VALUES(?,?,?,?)').bind(tag,x.equipamento,x.tipo_propriedade||'Próprio',x.fornecedor||null).run();eq={id:r.meta.last_row_id}}const ativo=await env.DB.prepare('SELECT id,status FROM ciclos WHERE equipamento_id=? AND finalizado_em IS NULL').bind(eq.id).first();if(ativo)return json({erro:'Já existe acompanhamento ativo para esta TAG.',processo:ativo},409);const max=await env.DB.prepare('SELECT max(numero) n FROM ciclos WHERE equipamento_id=?').bind(eq.id).first(),numero=(max?.n||0)+1;const r=await env.DB.prepare(`INSERT INTO ciclos(equipamento_id,numero,destino_id,os,processo,status,proxima_acao,prioridade,criado_por) VALUES(?,?,?,?,?,?,?,?,?)`).bind(eq.id,numero,x.destino_id,x.os||null,x.processo||'Fluxo normal','Solicitado Manutenção',x.proxima_acao||'Acompanhar autorização da manutenção',x.prioridade||'Normal',user.id).run();await env.DB.prepare('INSERT INTO historico(ciclo_id,usuario_id,status_novo,observacao) VALUES(?,?,?,?)').bind(r.meta.last_row_id,user.id,'Solicitado Manutenção','Ciclo criado').run();return json({id:r.meta.last_row_id,numero},201)}
let match=path.match(/^\/api\/ciclos\/(\d+)\/status$/);if(match&&method==='POST'){const x=await body(request),c=await env.DB.prepare('SELECT * FROM ciclos WHERE id=?').bind(match[1]).first();if(!c)return json({erro:'Ciclo não encontrado'},404);if(c.finalizado_em)return json({erro:'Ciclo já finalizado'},409);if(x.status==='Finalizado'&&c.status!=='Pronto para Saída')return json({erro:'A saída só pode finalizar um ciclo que esteja Pronto para Saída'},400);await env.DB.batch([env.DB.prepare(`UPDATE ciclos SET status=?,proxima_acao=?,ultima_movimentacao_em=CURRENT_TIMESTAMP,finalizado_em=CASE WHEN ?='Finalizado' THEN CURRENT_TIMESTAMP ELSE finalizado_em END WHERE id=?`).bind(x.status,x.proxima_acao||null,x.status,c.id),env.DB.prepare('INSERT INTO historico(ciclo_id,usuario_id,status_anterior,status_novo,observacao) VALUES(?,?,?,?,?)').bind(c.id,user.id,c.status,x.status,x.observacao||null)]);return json({ok:true})}
match=path.match(/^\/api\/historico\/(\d+)$/);if(match&&method==='GET')return json((await env.DB.prepare('SELECT * FROM historico WHERE ciclo_id=? ORDER BY id DESC').bind(match[1]).all()).results);
if(path==='/api/ux/padroes'&&method==='GET')return json((await env.DB.prepare('SELECT * FROM padroes_design WHERE ativo=1 ORDER BY categoria,id').all()).results);
if(path==='/api/ux/feedback'&&method==='POST'){const x=await body(request),tela=text(x.tela),comentario=text(x.comentario),avaliacao=x.avaliacao==null?null:Number(x.avaliacao);if(!tela||!comentario)return json({erro:'Informe a tela e a dificuldade encontrada'},400);const r=await env.DB.prepare('INSERT INTO feedback_ux(tela,comentario,avaliacao,usuario_id) VALUES(?,?,?,?)').bind(tela,comentario,avaliacao,user.id).run();return json({id:r.meta.last_row_id,mensagem:'Feedback registrado para análise'},201)}
if(path==='/api/ux/analisar'&&method==='POST'){const x=await body(request),tela=text(x.tela),problema=text(x.problema),recomendacao=text(x.recomendacao);if(!tela||!problema||!recomendacao)return json({erro:'Informe tela, problema e recomendação'},400);const a=await env.DB.prepare('INSERT INTO analises_ux(tela,contexto,resultado,criado_por) VALUES(?,?,?,?)').bind(tela,text(x.contexto)||null,'Sugestão gerada para aprovação',user.id).run(),s=await env.DB.prepare('INSERT INTO sugestoes_ux(analise_id,categoria,prioridade,problema,recomendacao,impacto) VALUES(?,?,?,?,?,?)').bind(a.meta.last_row_id,x.categoria||'Usabilidade',x.prioridade||'Média',problema,recomendacao,text(x.impacto)||null).run();return json({analise_id:a.meta.last_row_id,sugestao_id:s.meta.last_row_id},201)}
if(path==='/api/ux/sugestoes'&&method==='GET')return json((await env.DB.prepare(`SELECT s.*,a.tela,u.nome responsavel FROM sugestoes_ux s LEFT JOIN analises_ux a ON a.id=s.analise_id LEFT JOIN usuarios u ON u.id=s.responsavel_id ORDER BY CASE s.prioridade WHEN 'Crítica' THEN 1 WHEN 'Alta' THEN 2 WHEN 'Média' THEN 3 ELSE 4 END,s.id DESC`).all()).results);
match=path.match(/^\/api\/ux\/sugestoes\/(\d+)$/);if(match&&method==='PATCH'){if(user.perfil!=='Administrador')return json({erro:'Somente administradores podem decidir sobre sugestões'},403);const x=await body(request),atual=await env.DB.prepare('SELECT * FROM sugestoes_ux WHERE id=?').bind(match[1]).first();if(!atual)return json({erro:'Sugestão não encontrada'},404);const justificativa=text(x.justificativa);if(!justificativa)return json({erro:'Informe a justificativa da decisão'},400);await env.DB.batch([env.DB.prepare('UPDATE sugestoes_ux SET status=?,decidido_por=?,justificativa=?,atualizado_em=CURRENT_TIMESTAMP WHERE id=?').bind(x.status,user.id,justificativa,atual.id),env.DB.prepare('INSERT INTO historico_sugestoes_ux(sugestao_id,status_anterior,status_novo,usuario_id,justificativa) VALUES(?,?,?,?,?)').bind(atual.id,atual.status,x.status,user.id,justificativa)]);return json({ok:true})}
if(path==='/api/ux/resumo'&&method==='GET'){const t=await env.DB.prepare(`SELECT count(*) total,sum(CASE WHEN status='Pendente' THEN 1 ELSE 0 END) pendentes,sum(CASE WHEN prioridade='Crítica' AND status NOT IN ('Rejeitada','Implementada') THEN 1 ELSE 0 END) criticas,sum(CASE WHEN status='Implementada' THEN 1 ELSE 0 END) implementadas FROM sugestoes_ux`).first(),p=await env.DB.prepare('SELECT count(DISTINCT tela) total FROM analises_ux').first();return json({...t,telas_revisadas:p.total})}
return json({erro:'Rota não encontrada'},404)}

const setupPage=()=>new Response(`<!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>Configurar Gestão Operacional</title><style>body{margin:0;background:#071a2b;color:#142235;font:16px Arial;display:grid;place-items:center;min-height:100vh}.card{background:#fff;width:min(440px,88vw);padding:32px;border-radius:16px;box-shadow:0 20px 50px #0005}h1{color:#071a2b;margin-top:0}p{color:#52606d}label{display:block;font-weight:700;margin:16px 0 6px}input{box-sizing:border-box;width:100%;padding:13px;border:1px solid #b8c2cc;border-radius:8px}button{width:100%;margin-top:22px;padding:14px;border:0;border-radius:8px;background:#00a9c6;color:#fff;font-weight:700;cursor:pointer}.msg{margin-top:15px;font-weight:700}.ok{color:#14804a}.erro{color:#c62828}</style></head><body><main class="card"><h1>Primeiro acesso</h1><p>Cadastre o administrador do Gestão Operacional. Esta tela será bloqueada após o cadastro.</p><form id="f"><label>Nome</label><input name="nome" required><label>E-mail</label><input name="email" type="email" required><label>Nova senha</label><input name="senha" type="password" minlength="8" required><button>Criar acesso</button><div id="m" class="msg"></div></form></main><script>f.onsubmit=async e=>{e.preventDefault();m.textContent='Salvando...';m.className='msg';const x=Object.fromEntries(new FormData(f));const r=await fetch('/api/setup',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(x)}),j=await r.json();if(r.ok){m.textContent='Acesso criado. Redirecionando...';m.className='msg ok';setTimeout(()=>location.href='/',1200)}else{m.textContent=j.erro||'Não foi possível cadastrar';m.className='msg erro'}};</script></body></html>`,{headers:{'content-type':'text/html; charset=utf-8','cache-control':'no-store'}});
export default{async fetch(request,env){const url=new URL(request.url);try{if(url.pathname==='/health'){await ensureSchema(env);const u=await env.DB.prepare('SELECT id FROM usuarios LIMIT 1').first();return json({ok:true,banco:'cloudflare-d1',cadastro_pendente:!u})}if(url.pathname==='/setup')return setupPage();if(url.pathname.startsWith('/api/'))return await api(request,env,url.pathname);return env.ASSETS.fetch(request)}catch(error){console.error(error);return json({erro:'Serviço temporariamente indisponível',detalhe:String(error.message||error)},500)}}};
